baseURL = "https://orbiting.com/"
languageCode = "en-us"
title = "Orbiting - visual messages"

publishDir = "public"

disableKinds = ["taxonomy", "RSS",  "section"]

[Permalinks]
    page= "/:filename/"
